apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitcoin-node.fullname" . }}-rpc
  labels:
    {{- include "bitcoin-node.labels" . | nindent 4 }}
  {{- with .Values.service.rpc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.rpc.type }}
  ports:
    - name: rpc
      port: {{ include "bitcoin-node.rpcPort" . }}
      targetPort: rpc
      protocol: TCP
  selector:
    {{- include "bitcoin-node.selectorLabels" . | nindent 4 }}
