apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitcoin-node.fullname" . }}-headless
  labels:
    {{- include "bitcoin-node.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: rpc
      port: {{ include "bitcoin-node.rpcPort" . }}
      targetPort: rpc
      protocol: TCP
    - name: p2p
      port: {{ include "bitcoin-node.p2pPort" . }}
      targetPort: p2p
      protocol: TCP
  selector:
    {{- include "bitcoin-node.selectorLabels" . | nindent 4 }}
